import 'dart:math';

import '../models/task.dart';

class RandomTaskGenerator {
  static final _tasks = [
    Task(
        activity: "Bake Something Sweet!",
        interest: "cooking",
        icon: 0xe477,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Cook a favorite meal or Try a new Recipe",
        interest: "cooking",
        icon: 0xe477,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Try Making Candy",
        interest: "cooking",
        icon: 0xe477,
        completed: false,
        timeAssigned: ""),
    Task(
        activity:
            "Color a picture or coloring book (children or adult version)",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Create a movie or fun motion picture",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Create a scrapbook or photo book",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Create your own candle(s)",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Put together a care package",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Crochet something",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Draw, sketch, or tr ace a picture",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Decorate cookies or a cake that you’ve baked",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Do Needle Point",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Edit photos for keeping or sharing with others",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Knit something fun to stay warm in",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Make a collage of pictures",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Make a snow globe",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Make homemade slime",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Make homemade slime",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Paint something fun",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Record music",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Sew something cool",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Sculpt an interesting piece out of clay",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Take some Pictures",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Write a children’s story",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Write a Novel",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Write a Poem",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Write a letter to yourself in the future",
        interest: "fun",
        icon: 0xe5b1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Make lemonade",
        interest: "health",
        icon: 0xe3de,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Have a fruit salad",
        interest: "health",
        icon: 0xe3de,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Read a book before sleeping",
        interest: "health",
        icon: 0xe3de,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Take vitamins",
        interest: "health",
        icon: 0xe3de,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Stretch or Do Yoga",
        interest: "health",
        icon: 0xe3de,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Drink a full glass of water or a cup of tea",
        interest: "health",
        icon: 0xe3de,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Play Chess",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Play a musical instrument",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Read a book",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Write a journal",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Draw some sketches",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Write a blog article",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Draw a painting",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Dance on your favorite song",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Learn your favorite language",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Bake your favorite cake or bread",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Play a Solo Card Game (Like Solitaire)",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Sing your favorite songs",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "listen to a new audiobook",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Play a Classic or Retro Video Game",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Start an Indoor Garden",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity:
            "Clean and sanitize your phone, laptop, or tablet (and their cases!)",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "De-clutter your house",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Round up old items to donate",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Learn a Handyman skill",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Learn some computer keyboard shortcuts",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Change up your home décor",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Create and fly a paper airplane",
        interest: "indoor",
        icon: 0xe5e0,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Solve a Fun (or Challenging!) Puzzle",
        interest: "mind",
        icon: 0xe568,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Look at old photos & photo albums (or organize them!)",
        interest: "mind",
        icon: 0xe568,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Start writing a bucket list",
        interest: "mind",
        icon: 0xe568,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Read a Book or Magazine",
        interest: "mind",
        icon: 0xe568,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Listen to music",
        interest: "mind",
        icon: 0xe568,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Meditate to a video or audio course",
        interest: "mind",
        icon: 0xe568,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Listen to a podcast or the Radio",
        interest: "mind",
        icon: 0xe568,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Create a list of books You want to read",
        interest: "mind",
        icon: 0xe568,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Create a vision board for the year",
        interest: "mind",
        icon: 0xe568,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Make a budget or financial goal",
        interest: "mind",
        icon: 0xe568,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Update your gadgets",
        interest: "personal development",
        icon: 0xe499,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Update your contacts information",
        interest: "personal development",
        icon: 0xe499,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Update your Resume",
        interest: "personal development",
        icon: 0xe499,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Wash your homes windows",
        interest: "personal development",
        icon: 0xe499,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Wash your car",
        interest: "personal development",
        icon: 0xe499,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Work on your Amazon wishlist",
        interest: "personal development",
        icon: 0xe499,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Start a Journal",
        interest: "personal development",
        icon: 0xe499,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Write some online reviews for a recent purchase you made",
        interest: "personal development",
        icon: 0xe499,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Write your will",
        interest: "personal development",
        icon: 0xe499,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Make a Household Product",
        interest: "personal development",
        icon: 0xe499,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Express Gratitude towards someone you appreciate",
        interest: "personal development",
        icon: 0xe499,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "set professional goals for yourself",
        interest: "personal development",
        icon: 0xe499,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "set Personal goals for yourself",
        interest: "personal development",
        icon: 0xe499,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Organize a yard sale",
        interest: "personal development",
        icon: 0xe499,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Organize the apps on your phone",
        interest: "personal development",
        icon: 0xe499,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Set some personal goals for yourself",
        interest: "personal development",
        icon: 0xe499,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Sign up for a local class",
        interest: "personal development",
        icon: 0xe499,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Call your school friend",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Do a virtual dinner with family or friends",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Watch a movie",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Get your favorite drink",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Organize a Networking Event",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Attend a Networking Event",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Attend a Stand-up comedy show",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Host a small house party for friends or family",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Call someone you care about",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Message or Email someone you admire",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Browse your social media feeds",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Browse for an online learning course",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Read up on current events & news",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Trace down your ancestry & family hist",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Clean up your Facebook, Twitter, Instagram, etc",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Clean out your closet of old or unused clothes",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Secure your online accounts",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Clean up your emails",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Fine-tune your LinkedIn profile",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Go through the photos on your phone",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
    Task(
        activity: "Organize the apps on your phone",
        interest: "social",
        icon: 0xe3e1,
        completed: false,
        timeAssigned: ""),
  ];

  // static Task getRandomTask() {
  //   return _tasks[Random().nextInt(_tasks.length)];
  // }

  static List<Task> getTask() {
    return _tasks;
  }
}
